apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver
spec:
  selector:
    matchLabels:
      app: driver
  template:
    metadata:
      labels:
        app: driver
    spec:
      containers:
        - image: <driver-image>
          name: driver-container
          ports:
            - containerPort: 4567
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 4567
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: driver
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4567
      name: http
  selector:
    app: driver

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: driver
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: driver
              servicePort: 80
            path: /config